//! Google Docs reader and diff writer against recorded `documents.get`
//! responses (`tests/fixtures`, generated by `tools/make_gdoc_fixtures.py`).

use serde_json::Value;
use wp_core::model::*;
use wp_core::Editor;
use wp_gdoc::{batch_update, detach, diff, read, Loaded};

fn fixture(name: &str) -> String {
    std::fs::read_to_string(format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name)).unwrap()
}

fn load(name: &str) -> Loaded {
    read(&fixture(name)).unwrap()
}

/// The one request kind in a request object, and its body.
fn kind(r: &Value) -> (&str, &Value) {
    let (k, v) = r.as_object().unwrap().iter().next().unwrap();
    (k.as_str(), v)
}

fn range(v: &Value) -> (i64, i64) {
    (v["range"]["startIndex"].as_i64().unwrap(), v["range"]["endIndex"].as_i64().unwrap())
}

fn kinds(reqs: &[Value]) -> Vec<String> {
    reqs.iter().map(|r| kind(r).0.to_string()).collect()
}

fn para_text(doc: &wp_core::Document, i: usize) -> String {
    doc.paragraphs[i].items.iter().map(|it| match it {
        Item::Char(c) => c.to_string(),
        Item::Code(Code::Tab) => "\t".into(),
        Item::Code(Code::LineBreak) => "\u{b}".into(),
        _ => String::new(),
    }).collect()
}

fn attrs_at(doc: &wp_core::Document, para: usize, idx: usize) -> RunProps {
    doc.run_props_at(Pos::new(para, idx))
}

// ---------------------------------------------------------------- reading

#[test]
fn reads_body_structure() {
    let l = load("report.json");
    let d = &l.doc;
    assert_eq!(l.baseline.document_id, "1AbCdEfGhIjKlMnOpQrStUvWxYz");
    assert_eq!(l.baseline.revision_id, "ALBJ4LtRev1");
    assert_eq!(l.baseline.title, "Quarterly Report");
    // Heading, body para, two bullets, tab para, 4 cells, figure, page break, last.
    assert_eq!(d.paragraphs.len(), 12);
    assert_eq!(para_text(d, 0), "Quarterly Report");
    assert_eq!(d.paragraphs[0].props.style.as_deref(), Some("Heading1"));
    assert_eq!(para_text(d, 1), "The results were published.");
    assert_eq!(para_text(d, 4), "Name:\tValue\u{b}Second line");
    assert_eq!(d.paragraphs[4].props.align, Some(Align::Center));
    assert_eq!(d.paragraphs[4].props.tabs.len(), 1);
    assert_eq!(d.paragraphs[4].props.tabs[0].pos, 144 * 20);
    assert_eq!(para_text(d, 11), "Café — naïve 😀 end.");
    assert_eq!(d.paragraphs[11].props.space_before, Some(240));
    assert_eq!(d.paragraphs[11].props.line_spacing, Some(LineSpacing::Auto(360)));
    // Page geometry.
    assert_eq!(d.section.page_width, 12240);
    assert_eq!(d.section.margin_left, 1440);
    // Named styles landed in the sheet.
    assert_eq!(d.styles.get("Normal").unwrap().run.font.as_deref(), Some("Arial"));
    assert_eq!(d.styles.get("Heading1").unwrap().run.size, Some(40));
    assert!(l.warnings.is_empty(), "{:?}", l.warnings);
}

#[test]
fn reads_character_formatting_and_links() {
    let l = load("report.json");
    let d = &l.doc;
    // "The results were published." — bold on "results", link on "published".
    let bold_at = para_text(d, 1).find("results").unwrap();
    let idx = d.paragraphs[1].items.iter().enumerate().filter(|(_, it)| !it.is_code()).nth(bold_at).unwrap().0;
    assert!(attrs_at(d, 1, idx + 1).is_bold());
    let pub_at = para_text(d, 1).find("published").unwrap();
    let idx = d.paragraphs[1].items.iter().enumerate().filter(|(_, it)| !it.is_code()).nth(pub_at).unwrap().0;
    let rp = attrs_at(d, 1, idx + 1);
    assert_eq!(rp.underline(), Some(Underline::Single));
    assert!(d.attrs_at(Pos::new(1, idx + 1)).contains_key(&AttrKind::CharStyle));
    assert!(d.paragraphs[1].items.iter().any(|it| matches!(it, Item::Code(Code::Opaque(o)) if o.xml.starts_with("<w:hyperlink r:id=\"rIdgd1\""))));
    assert_eq!(d.extra_rels[0].target, "https://example.com/report");
    // Last paragraph: italic 14pt red on yellow (after its four opening codes).
    let rp = attrs_at(d, 11, 5);
    assert!(rp.is_italic());
    assert_eq!(rp.size, Some(28));
    assert_eq!(rp.color, Some(Rgb(255, 0, 0)));
    assert_eq!(rp.highlight(), Some(Highlight::Yellow));
}

#[test]
fn reads_lists_tables_footnotes_and_objects() {
    let l = load("report.json");
    let d = &l.doc;
    let lr = d.paragraphs[2].props.list.unwrap();
    assert_eq!(lr.level, 0);
    assert!(d.numbering.is_bullet(lr.num_id, 0));
    assert_eq!(d.paragraphs[3].props.list, Some(lr));
    // The list's indent lives on the level, not the paragraph.
    assert_eq!(d.paragraphs[2].props.indent_left, None);
    assert_eq!(d.paragraphs[2].props.hanging, None);
    let lvl = d.numbering.level(lr.num_id, 0).unwrap();
    assert_eq!(lvl.para.indent_left, Some(720));
    assert_eq!(lvl.para.hanging, Some(360));
    assert_eq!(lvl.text, "●");
    assert_eq!(d.numbering.level(lr.num_id, 1).unwrap().para.indent_left, Some(1440));
    // Table: 2×2, cells tagged, grid from column widths.
    let cells: Vec<(String, CellRef)> = (5..9).map(|i| (para_text(d, i), d.paragraphs[i].props.cell.unwrap())).collect();
    assert_eq!(cells[0].0, "A1");
    assert_eq!(cells[3].0, "B2");
    assert_eq!(cells[3].1, CellRef::new(cells[0].1.table, 1, 1));
    let t = &d.tables[&cells[0].1.table];
    assert_eq!(t.grid, vec![4680, 4680]);
    // Footnote reference and body.
    assert!(d.paragraphs[1].items.iter().any(|it| matches!(it, Item::Code(Code::Opaque(o)) if o.xml == "<w:footnoteReference w:id=\"1\"/>")));
    assert_eq!(d.footnotes.len(), 1);
    assert_eq!(d.footnotes[0].paragraphs[0].text(), "Source: annual filing.");
    assert_eq!(l.baseline.footnote_ids, vec!["kix.fn1".to_string()]);
    // Image and page break.
    assert!(d.paragraphs[9].items.iter().any(|it| matches!(it, Item::Code(Code::Opaque(o)) if o.label == "Image" && o.xml.starts_with('{'))));
    assert!(d.paragraphs[10].items.iter().any(|it| matches!(it, Item::Code(Code::PageBreak))));
}

#[test]
fn reads_tabs_form() {
    let l = load("report-tabs.json");
    assert_eq!(l.baseline.tab_id.as_deref(), Some("t.0"));
    assert_eq!(l.doc.paragraphs.len(), 12);
    // Every request names the tab.
    let mut ed = Editor::new(l.doc.clone());
    ed.move_to(Pos::new(0, 0), false);
    ed.insert_str("X");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert!(!reqs.is_empty());
    for r in &reqs {
        let (_, body) = kind(r);
        let loc = body.get("location").or_else(|| body.get("range")).unwrap();
        assert_eq!(loc["tabId"], "t.0");
    }
}

#[test]
fn reads_numbered_lists_and_suggestions() {
    let l = load("numbered.json");
    let d = &l.doc;
    let lr = d.paragraphs[1].props.list.unwrap();
    assert!(!d.numbering.is_bullet(lr.num_id, 0));
    assert_eq!(d.numbering.level(lr.num_id, 0).unwrap().text, "%1.");
    assert_eq!(d.numbering.level(lr.num_id, 1).unwrap().text, "%2.");
    assert_eq!(d.numbering.level(lr.num_id, 1).unwrap().fmt, wp_core::numbering::NumFmt::LowerLetter);
    assert_eq!(d.paragraphs[2].props.list.unwrap().level, 1);
    assert_eq!(d.paragraphs[2].props.indent_left, None);
    assert_eq!(d.paragraphs[3].props.list, Some(lr));
    // Suggestions become protected tracked-change wrappers.
    let ins = d.paragraphs[4].items.iter().find_map(|it| match it {
        Item::Code(Code::Opaque(o)) if o.xml.starts_with("<w:ins") => Some(o.clone()),
        _ => None,
    }).unwrap();
    assert!(ins.protected);
    let del = d.paragraphs[5].items.iter().find_map(|it| match it {
        Item::Code(Code::Opaque(o)) if o.xml.starts_with("<w:del") => Some(o.clone()),
        _ => None,
    }).unwrap();
    assert!(del.deleted);
    assert_eq!(l.warnings, vec!["2 suggestions shown as tracked changes".to_string()]);
}

// ---------------------------------------------------------------- writing

#[test]
fn untouched_document_produces_no_requests() {
    for f in ["report.json", "report-tabs.json", "numbered.json"] {
        let l = load(f);
        assert_eq!(diff(&l.baseline, &l.doc).unwrap(), Vec::<Value>::new(), "{}", f);
        // Through the editor too (it normalises nothing on load).
        let ed = Editor::new(l.doc.clone());
        assert_eq!(diff(&l.baseline, &ed.doc).unwrap(), Vec::<Value>::new(), "{}", f);
    }
}

#[test]
fn typing_inserts_text_at_the_utf16_index() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    // After "The " in paragraph 1 (Docs index 18 + 4).
    ed.move_to(Pos::new(1, 4), false);
    ed.insert_str("new ");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert_eq!(kinds(&reqs), vec!["insertText", "updateTextStyle"]);
    assert_eq!(reqs[0]["insertText"]["location"]["index"], 22);
    assert_eq!(reqs[0]["insertText"]["text"], "new ");
    assert!(reqs[0]["insertText"]["location"].get("segmentId").is_none());
    // The typed text is reset to the paragraph's own formatting.
    assert_eq!(range(&reqs[1]["updateTextStyle"]), (22, 26));
    assert_eq!(reqs[1]["updateTextStyle"]["fields"], "bold,italic,underline,strikethrough,smallCaps,fontSize,weightedFontFamily,foregroundColor,backgroundColor,baselineOffset,link");
    assert_eq!(reqs[1]["updateTextStyle"]["textStyle"], serde_json::json!({}));
}

#[test]
fn typing_after_an_emoji_counts_surrogate_pairs() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    // Paragraph 11 starts at 124: "Café — naïve 😀 end." — insert after the emoji.
    let n = para_text(&l.doc, 11).find("😀").unwrap();
    let chars_before = para_text(&l.doc, 11)[..n].chars().count();
    let idx = l.doc.paragraphs[11].items.iter().enumerate().filter(|(_, it)| !it.is_code()).nth(chars_before + 1).unwrap().0;
    ed.move_to(Pos::new(11, idx), false);
    ed.insert_str("!");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert_eq!(kind(&reqs[0]).0, "insertText");
    // "Café — naïve " is 13 UTF-16 units, the emoji is 2.
    assert_eq!(reqs[0]["insertText"]["location"]["index"], 124 + 13 + 2);
    // Typed inside italic red text: the reset carries those values.
    let ts = &reqs[1]["updateTextStyle"]["textStyle"];
    assert_eq!(ts["italic"], true);
    assert_eq!(ts["fontSize"]["magnitude"], 14.0);
    assert_eq!(ts["foregroundColor"]["color"]["rgbColor"]["red"], 1.0);
    assert_eq!(ts["backgroundColor"]["color"]["rgbColor"]["green"], 1.0);
}

#[test]
fn deleting_text_is_one_range() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    // Delete "results " with its bold pair (from the `[BOLD]` code on).
    let text = para_text(&l.doc, 1);
    let s = text.find("results").unwrap();
    let items = &l.doc.paragraphs[1].items;
    let idx_of = |n: usize| items.iter().enumerate().filter(|(_, it)| !it.is_code()).nth(n).unwrap().0;
    ed.delete_range(Range::new(Pos::new(1, idx_of(s) - 1), Pos::new(1, idx_of(s + 8))));
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert_eq!(kinds(&reqs), vec!["deleteContentRange"]);
    assert_eq!(range(&reqs[0]["deleteContentRange"]), (22, 30));
}

#[test]
fn bolding_a_word_updates_only_bold() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    // Bold "Quarterly" (heading paragraph at 1).
    ed.move_to(Pos::new(0, 0), false);
    ed.move_to(Pos::new(0, 9), true);
    ed.toggle_attr(Attr::Bold(true));
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert_eq!(kinds(&reqs), vec!["updateTextStyle"]);
    assert_eq!(range(&reqs[0]["updateTextStyle"]), (1, 10));
    assert_eq!(reqs[0]["updateTextStyle"]["fields"], "bold");
    assert_eq!(reqs[0]["updateTextStyle"]["textStyle"], serde_json::json!({ "bold": true }));
}

#[test]
fn unbolding_resets_the_field() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    let items = &l.doc.paragraphs[1].items;
    let on = items.iter().position(|it| matches!(it, Item::Code(Code::On(Attr::Bold(true))))).unwrap();
    let off = items.iter().position(|it| matches!(it, Item::Code(Code::Off(AttrKind::Bold)))).unwrap();
    ed.move_to(Pos::new(1, on + 1), false);
    ed.move_to(Pos::new(1, off), true);
    ed.set_attr(AttrKind::Bold, None);
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert_eq!(kinds(&reqs), vec!["updateTextStyle"]);
    assert_eq!(range(&reqs[0]["updateTextStyle"]), (22, 29));
    assert_eq!(reqs[0]["updateTextStyle"]["fields"], "bold");
    assert_eq!(reqs[0]["updateTextStyle"]["textStyle"], serde_json::json!({}));
}

#[test]
fn paragraph_formatting_diffs_fields() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    d.paragraphs[2].props.align = Some(Align::Right);
    d.paragraphs[2].props.touch();
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["updateParagraphStyle"]);
    let u = &reqs[0]["updateParagraphStyle"];
    assert_eq!(range(u), (47, 48));
    assert_eq!(u["fields"], "alignment");
    assert_eq!(u["paragraphStyle"]["alignment"], "END");
    // Changing the style name.
    let mut d = l.doc.clone();
    d.paragraphs[0].props.style = Some("Heading2".into());
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(reqs[0]["updateParagraphStyle"]["paragraphStyle"]["namedStyleType"], "HEADING_2");
    assert_eq!(reqs[0]["updateParagraphStyle"]["fields"], "namedStyleType");
}

#[test]
fn removing_and_adding_bullets() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    d.paragraphs[3].props.list = None;
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["updateParagraphStyle", "deleteParagraphBullets"]);
    assert_eq!(range(&reqs[1]["deleteParagraphBullets"]), (58, 59));
    let mut d = l.doc.clone();
    let lr = d.paragraphs[2].props.list;
    d.paragraphs[4].props.list = lr;
    let reqs = diff(&l.baseline, &d).unwrap();
    // The joining paragraph takes the level's indent, then its bullet.
    assert_eq!(kinds(&reqs), vec!["updateParagraphStyle", "createParagraphBullets"]);
    assert_eq!(reqs[0]["updateParagraphStyle"]["paragraphStyle"]["indentStart"]["magnitude"], 36.0);
    assert_eq!(reqs[1]["createParagraphBullets"]["bulletPreset"], "BULLET_DISC_CIRCLE_SQUARE");
    let l = load("numbered.json");
    let mut d = l.doc.clone();
    d.paragraphs[6].props.list = d.paragraphs[1].props.list;
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(reqs[1]["createParagraphBullets"]["bulletPreset"], "NUMBERED_DECIMAL_ALPHA_ROMAN");
}

#[test]
fn deleting_a_middle_paragraph() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    d.paragraphs.remove(3); // "Costs down" 58..69
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["deleteContentRange"]);
    assert_eq!(range(&reqs[0]["deleteContentRange"]), (58, 69));
}

#[test]
fn deleting_the_last_paragraph_keeps_the_final_newline() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    d.paragraphs.remove(11); // 124..145, after the page-break paragraph 122..124
    let reqs = diff(&l.baseline, &d).unwrap();
    // The previous paragraph's newline goes instead, then the survivor is
    // restyled in full because it now ends with the deleted paragraph's newline.
    assert_eq!(kinds(&reqs), vec!["deleteContentRange", "updateParagraphStyle"]);
    assert_eq!(range(&reqs[0]["deleteContentRange"]), (123, 144));
    let u = &reqs[1]["updateParagraphStyle"];
    assert_eq!(range(u), (122, 123));
    assert_eq!(u["fields"], wp_gdoc::project::P_ALL);
    assert_eq!(u["paragraphStyle"]["namedStyleType"], "NORMAL_TEXT");
}

#[test]
fn splitting_a_paragraph() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    // Enter after "Revenue" in "Revenue up" (47..58).
    ed.move_to(Pos::new(2, 7), false);
    ed.newline();
    assert_eq!(para_text(&ed.doc, 2), "Revenue");
    assert_eq!(para_text(&ed.doc, 3), " up");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    // Insert the new paragraph first (higher index), then trim the old one.
    let k = kinds(&reqs);
    assert_eq!(k[0], "insertText");
    assert_eq!(reqs[0]["insertText"]["location"]["index"], 57);
    assert_eq!(reqs[0]["insertText"]["text"], "\n up");
    // New paragraph at 58..61: text reset, paragraph style in full, bullets kept.
    let ts = reqs.iter().find(|r| kind(r).0 == "updateTextStyle").unwrap();
    assert_eq!(range(&ts["updateTextStyle"]), (58, 61));
    let ps = reqs.iter().find(|r| kind(r).0 == "updateParagraphStyle").unwrap();
    assert_eq!(range(&ps["updateParagraphStyle"]), (58, 59));
    assert_eq!(ps["updateParagraphStyle"]["fields"], wp_gdoc::project::P_ALL);
    assert_eq!(ps["updateParagraphStyle"]["paragraphStyle"]["indentStart"]["magnitude"], 36.0);
    assert!(!k.contains(&"deleteParagraphBullets".to_string()));
    assert!(!k.contains(&"createParagraphBullets".to_string()));
    let del = reqs.iter().find(|r| kind(r).0 == "deleteContentRange").unwrap();
    assert_eq!(range(&del["deleteContentRange"]), (54, 57));
    // The delete comes after the insert.
    assert!(reqs.iter().position(|r| kind(r).0 == "deleteContentRange") > reqs.iter().position(|r| kind(r).0 == "insertText"));
}

#[test]
fn joining_two_paragraphs() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    // Backspace at the start of "Costs down" joins it to "Revenue up".
    ed.move_to(Pos::new(3, 0), false);
    ed.backspace(false);
    assert_eq!(para_text(&ed.doc, 2), "Revenue upCosts down");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    let k = kinds(&reqs);
    // Delete the second paragraph, extend the first.
    assert!(k.contains(&"deleteContentRange".to_string()));
    assert!(k.contains(&"insertText".to_string()));
    let del = reqs.iter().find(|r| kind(r).0 == "deleteContentRange").unwrap();
    assert_eq!(range(&del["deleteContentRange"]), (58, 69));
    let ins = reqs.iter().find(|r| kind(r).0 == "insertText").unwrap();
    assert_eq!(ins["insertText"]["location"]["index"], 57);
    assert_eq!(ins["insertText"]["text"], "Costs down");
}

#[test]
fn appending_a_paragraph_at_the_end() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    ed.move_to(l.doc.end_pos(), false);
    ed.newline();
    ed.insert_str("Fin");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert_eq!(kinds(&reqs), vec!["insertText", "updateTextStyle", "updateParagraphStyle"]);
    assert_eq!(reqs[0]["insertText"]["location"]["index"], 144);
    assert_eq!(reqs[0]["insertText"]["text"], "\nFin");
    assert_eq!(range(&reqs[1]["updateTextStyle"]), (145, 148));
    assert_eq!(range(&reqs[2]["updateParagraphStyle"]), (145, 146));
    // Enter copies the paragraph's properties, so the new one is set in full.
    assert_eq!(reqs[2]["updateParagraphStyle"]["fields"], wp_gdoc::project::P_ALL);
    let ps = &reqs[2]["updateParagraphStyle"]["paragraphStyle"];
    assert_eq!(ps["spaceAbove"]["magnitude"], 12.0);
    assert_eq!(ps["namedStyleType"], "NORMAL_TEXT");
}

#[test]
fn inserting_a_paragraph_at_the_start() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    d.paragraphs.insert(0, Paragraph::from_text("Preface"));
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kind(&reqs[0]).0, "insertText");
    assert_eq!(reqs[0]["insertText"]["location"]["index"], 1);
    assert_eq!(reqs[0]["insertText"]["text"], "Preface\n");
    assert_eq!(range(&reqs[1]["updateTextStyle"]), (1, 8));
    assert_eq!(range(&reqs[2]["updateParagraphStyle"]), (1, 2));
}

#[test]
fn several_edits_come_out_in_descending_order() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    ed.move_to(Pos::new(0, 0), false);
    ed.insert_str("A ");
    ed.move_to(Pos::new(3, 0), false);
    ed.insert_str("B ");
    ed.move_to(Pos::new(11, 0), false);
    ed.insert_str("C ");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    let inserts: Vec<i64> = reqs.iter().filter(|r| kind(r).0 == "insertText").map(|r| r["insertText"]["location"]["index"].as_i64().unwrap()).collect();
    assert_eq!(inserts.len(), 3);
    assert!(inserts.windows(2).all(|w| w[0] > w[1]), "{:?}", inserts);
    assert!(inserts[0] >= 124 && inserts[1] == 58 && inserts[2] == 1, "{:?}", inserts);
}

#[test]
fn table_cell_edits_address_the_cell() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    // Cell B2 is paragraph 8 at 109..112.
    ed.move_to(Pos::new(8, 2), false);
    ed.insert_str("!");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert_eq!(kind(&reqs[0]).0, "insertText");
    assert_eq!(reqs[0]["insertText"]["location"]["index"], 111);
}

#[test]
fn table_shape_changes_are_refused() {
    let l = load("report.json");
    let mut ed = Editor::new(l.doc.clone());
    ed.move_to(Pos::new(8, 0), false);
    assert!(ed.insert_row(true));
    let err = diff(&l.baseline, &ed.doc).unwrap_err();
    assert!(err.contains("table"), "{}", err);
    let mut ed = Editor::new(l.doc.clone());
    ed.move_to(Pos::new(2, 0), false);
    assert!(ed.insert_table(2, 2));
    assert!(diff(&l.baseline, &ed.doc).is_err());
}

#[test]
fn footnote_edits_name_the_segment() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    d.footnotes[0].paragraphs[0].items.insert(0, Item::Char('*'));
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kind(&reqs[0]).0, "insertText");
    assert_eq!(reqs[0]["insertText"]["location"]["index"], 0);
    assert_eq!(reqs[0]["insertText"]["location"]["segmentId"], "kix.fn1");
    assert_eq!(reqs[1]["updateTextStyle"]["range"]["segmentId"], "kix.fn1");
}

#[test]
fn deleted_footnote_reference_skips_its_body() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    // Delete the reference (and its superscript codes) from paragraph 1.
    let items = &mut d.paragraphs[1].items;
    let i = items.iter().position(|it| matches!(it, Item::Code(Code::Opaque(o)) if o.label == "Footnote")).unwrap();
    items.drain(i - 1..i + 2);
    d.footnotes[0].paragraphs[0].items.insert(0, Item::Char('*'));
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["deleteContentRange"]);
    assert_eq!(range(&reqs[0]["deleteContentRange"]), (45, 46));
}

#[test]
fn page_breaks_and_images_move_with_their_paragraph_but_not_into_new_ones() {
    let l = load("report.json");
    // Typing before the page break: the break stays where it is.
    let mut ed = Editor::new(l.doc.clone());
    ed.move_to(Pos::new(10, 0), false);
    ed.insert_str("x");
    let reqs = diff(&l.baseline, &ed.doc).unwrap();
    assert_eq!(kind(&reqs[0]).0, "insertText");
    assert_eq!(reqs[0]["insertText"]["location"]["index"], 122);
    // A page break typed into an existing paragraph is inserted as one.
    let mut d = l.doc.clone();
    d.paragraphs[0].items.push(Item::Code(Code::PageBreak));
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["insertPageBreak"]);
    assert_eq!(reqs[0]["insertPageBreak"]["location"]["index"], 17);
    // An image cannot be moved into a brand-new paragraph (yet).
    let mut d = l.doc.clone();
    let img = d.paragraphs[9].items.pop().unwrap();
    d.paragraphs.push(Paragraph { props: ParaProps::default(), items: vec![img] });
    assert!(diff(&l.baseline, &d).unwrap_err().contains("image"));
}

#[test]
fn deleting_an_image_deletes_its_index() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    d.paragraphs[9].items.pop();
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["deleteContentRange"]);
    assert_eq!(range(&reqs[0]["deleteContentRange"]), (120, 121));
}

#[test]
fn batch_update_pins_the_revision() {
    let l = load("report.json");
    let body = batch_update(&l.baseline, vec![serde_json::json!({ "insertText": { "location": { "index": 1 }, "text": "x" } })]);
    assert_eq!(body["writeControl"]["requiredRevisionId"], "ALBJ4LtRev1");
    assert_eq!(body["requests"].as_array().unwrap().len(), 1);
}

#[test]
fn detach_strips_what_only_docs_can_hold() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    let dropped = detach(&mut d);
    assert_eq!(dropped, vec!["Image".to_string()]);
    assert!(!d.paragraphs.iter().any(|p| p.items.iter().any(|it| matches!(it, Item::Code(Code::Opaque(o)) if o.xml.starts_with('{')))));
    // Hyperlinks, footnotes and tracked changes are ordinary `.docx` shapes and stay.
    assert!(d.paragraphs[1].items.iter().any(|it| matches!(it, Item::Code(Code::Opaque(o)) if o.xml.starts_with("<w:hyperlink"))));
}

#[test]
fn leaving_a_list_resets_its_indent() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    // Enter twice in wp: the paragraph leaves the list and keeps no indent.
    d.paragraphs[3].props.list = None;
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["updateParagraphStyle", "deleteParagraphBullets"]);
    let u = &reqs[0]["updateParagraphStyle"];
    assert_eq!(u["fields"], "indentStart,indentFirstLine");
    assert!(u["paragraphStyle"].get("indentStart").is_none());
}

#[test]
fn changing_list_level_changes_the_indent_not_the_list() {
    let l = load("numbered.json");
    let mut d = l.doc.clone();
    // Tab on "Second": level 0 → 1 within the same list.
    d.paragraphs[3].props.list.as_mut().unwrap().level = 1;
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["updateParagraphStyle"]);
    let u = &reqs[0]["updateParagraphStyle"];
    assert_eq!(u["fields"], "indentStart,indentFirstLine");
    assert_eq!(u["paragraphStyle"]["indentStart"]["magnitude"], 72.0);
    assert_eq!(u["paragraphStyle"]["indentFirstLine"]["magnitude"], 54.0);
}

#[test]
fn a_new_nested_bullet_is_created_with_leading_tabs() {
    let l = load("report.json");
    let mut d = l.doc.clone();
    let mut lr = d.paragraphs[2].props.list.unwrap();
    lr.level = 1;
    d.paragraphs[4].props.list = Some(lr);
    let reqs = diff(&l.baseline, &d).unwrap();
    assert_eq!(kinds(&reqs), vec!["updateParagraphStyle", "insertText", "createParagraphBullets"]);
    assert_eq!(reqs[1]["insertText"]["text"], "\t");
    assert_eq!(reqs[1]["insertText"]["location"]["index"], 69);
    assert_eq!(range(&reqs[2]["createParagraphBullets"]), (69, 70));
}
