//! The command registry. Every capability is a command; keys and the palette
//! both resolve to entries here, so nothing can be reachable by key but
//! missing from the palette (DESIGN.md §7.1).

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Cmd {
    // File
    New,
    Open,
    OpenFromDrive,
    GoogleSignOut,
    Save,
    SaveAs,
    SaveAsText,
    SaveAsDocx,
    SaveAsMarkdown,
    Exit,
    Warnings,
    // Edit
    Undo,
    Redo,
    Cut,
    Copy,
    Paste,
    PastePlain,
    PasteFromRing,
    SelectAll,
    Block,
    DeleteWord,
    DeleteWordBack,
    DeleteToEndOfLine,
    DeleteToStartOfLine,
    Typeover,
    Cancel,
    // Character formatting
    Bold,
    Italic,
    Underline,
    DoubleUnderline,
    Strikethrough,
    Superscript,
    Subscript,
    SmallCaps,
    AllCaps,
    Font,
    FontSize,
    FontColor,
    Highlight,
    RemoveFormatting,
    // Paragraph formatting
    AlignLeft,
    AlignCenter,
    AlignRight,
    AlignJustify,
    Indent,
    Outdent,
    IndentLeftRight,
    HangingIndent,
    ClearIndent,
    FirstLineIndent,
    SpacingSingle,
    SpacingOneHalf,
    SpacingDouble,
    SpaceBefore,
    SpaceAfter,
    KeepWithNext,
    KeepLinesTogether,
    PageBreakBefore,
    WidowOrphan,
    TabSet,
    // Lists
    ListBullet,
    ListNumber,
    ListFormat,
    ListIndent,
    ListOutdent,
    ListRestart,
    ListContinue,
    ListRemove,
    // Styles
    ApplyStyle,
    StyleNormal,
    StyleHeading1,
    StyleHeading2,
    StyleHeading3,
    StyleTitle,
    StyleBrowser,
    // Insert
    PageBreak,
    LineBreak,
    InsertTab,
    Bookmark,
    Date,
    // Table
    TableInsert,
    TableNextCell,
    TablePrevCell,
    TableInsertRowBelow,
    TableInsertRowAbove,
    TableInsertColRight,
    TableInsertColLeft,
    TableDeleteRow,
    TableDeleteCol,
    TableDelete,
    TableToText,
    TableColWidth,
    TableHeaderRow,
    // Page
    SectionBreakNextPage,
    SectionBreakContinuous,
    SectionBreakOddPage,
    SectionBreakEvenPage,
    ColumnsOne,
    ColumnsTwo,
    ColumnsThree,
    HeaderEdit,
    HeaderEditFirst,
    HeaderEditEven,
    FooterEdit,
    FooterEditFirst,
    FooterEditEven,
    HeaderFooterDone,
    HeaderRemove,
    FooterRemove,
    TitlePage,
    EvenOddHeaders,
    InsertPageNumber,
    InsertPageCount,
    PageSetup,
    PaperLetter,
    PaperA4,
    Landscape,
    Portrait,
    Margins,
    // View
    RevealCodes,
    RevealAllCodes,
    ToggleView,
    ToggleWrap,
    FkeyLegend,
    MenuBar,
    ThemeDefault,
    ThemeClassic,
    WordCount,
    Redraw,
    // Navigation
    Palette,
    Menu,
    GoToPage,
    GoToHeading,
    GoToBookmark,
    Find,
    FindBackward,
    FindNext,
    FindPrev,
    FindRegex,
    FindToggleCase,
    FindToggleWord,
    FindToggleRegex,
    FindBold,
    FindItalic,
    FindUnderlined,
    FindHighlighted,
    FindInStyle,
    FindCode,
    FindPageBreak,
    FindTab,
    FindLineBreak,
    Replace,
    MoveLeft,
    MoveRight,
    MoveUp,
    MoveDown,
    WordLeft,
    WordRight,
    LineStart,
    LineEnd,
    ParaUp,
    ParaDown,
    PageUp,
    PageDown,
    DocStart,
    DocEnd,
    NextPage,
    PrevPage,
    SelectLeft,
    SelectRight,
    SelectUp,
    SelectDown,
    SelectWordLeft,
    SelectWordRight,
    SelectLineStart,
    SelectLineEnd,
    SelectDocStart,
    SelectDocEnd,
    SelectPageUp,
    SelectPageDown,
    // Keyboard / help
    KeyboardClassic,
    KeyboardModern,
    Help,
    About,
    // Editing keys
    Backspace,
    Delete,
    Enter,
    // Repeat-count prefix (classic Esc)
    RepeatPrefix,
}

pub struct Command {
    pub id: Cmd,
    /// Stable id used in config bindings.
    pub key: &'static str,
    pub title: &'static str,
    pub category: &'static str,
    /// Extra words the palette should match.
    pub aliases: &'static str,
    /// Listed in the palette (plain cursor keys are not).
    pub listed: bool,
}

macro_rules! cmd {
    ($id:ident, $key:literal, $title:literal, $cat:literal) => {
        Command { id: Cmd::$id, key: $key, title: $title, category: $cat, aliases: "", listed: true }
    };
    ($id:ident, $key:literal, $title:literal, $cat:literal, $aliases:literal) => {
        Command { id: Cmd::$id, key: $key, title: $title, category: $cat, aliases: $aliases, listed: true }
    };
    (hidden $id:ident, $key:literal, $title:literal, $cat:literal) => {
        Command { id: Cmd::$id, key: $key, title: $title, category: $cat, aliases: "", listed: false }
    };
}

pub static COMMANDS: &[Command] = &[
    cmd!(New, "new", "New Document", "File"),
    cmd!(Open, "open", "Open…", "File", "retrieve list files"),
    cmd!(OpenFromDrive, "open-drive", "Open from Google Drive…", "File", "google docs cloud gdoc"),
    cmd!(GoogleSignOut, "google-sign-out", "Sign Out of Google", "File", "drive docs token"),
    cmd!(Save, "save", "Save", "File"),
    cmd!(SaveAs, "save-as", "Save As…", "File"),
    cmd!(SaveAsDocx, "save-as-docx", "Save As Word Document (.docx)…", "File", "export"),
    cmd!(SaveAsMarkdown, "save-as-markdown", "Save As Markdown (.md)…", "File", "export commonmark"),
    cmd!(SaveAsText, "save-as-text", "Save As Plain Text (.txt)…", "File", "export"),

    cmd!(Exit, "exit", "Exit", "File", "quit close"),
    cmd!(Warnings, "warnings", "Warnings — Unsupported Content in This Document", "File", "preserved comments tracked changes"),
    cmd!(Undo, "undo", "Undo", "Edit"),
    cmd!(Redo, "redo", "Redo", "Edit"),
    cmd!(Cut, "cut", "Cut", "Edit", "move block"),
    cmd!(Copy, "copy", "Copy", "Edit"),
    cmd!(Paste, "paste", "Paste", "Edit", "retrieve"),
    cmd!(PastePlain, "paste-plain", "Paste as Plain Text", "Edit", "unformatted"),
    cmd!(PasteFromRing, "paste-ring", "Paste from Cut History…", "Edit", "undelete clipboard ring"),
    cmd!(SelectAll, "select-all", "Select All", "Edit"),
    cmd!(Block, "block", "Block (Start Selection)", "Edit", "select mark"),
    cmd!(DeleteWord, "delete-word", "Delete Next Word", "Edit", "forward"),
    cmd!(DeleteWordBack, "delete-word-back", "Delete Previous Word", "Edit", "backward backspace"),
    cmd!(DeleteToEndOfLine, "delete-eol", "Delete to End of Line", "Edit", "kill line"),
    cmd!(DeleteToStartOfLine, "delete-bol", "Delete to Start of Line", "Edit", "kill backward"),
    cmd!(Typeover, "typeover", "Toggle Typeover (Insert/Overwrite)", "Edit"),
    cmd!(Cancel, "cancel", "Cancel", "Edit", "escape"),
    cmd!(Bold, "bold", "Bold", "Format ▸ Character"),
    cmd!(Italic, "italic", "Italic", "Format ▸ Character"),
    cmd!(Underline, "underline", "Underline", "Format ▸ Character"),
    cmd!(DoubleUnderline, "double-underline", "Double Underline", "Format ▸ Character"),
    cmd!(Strikethrough, "strikethrough", "Strikethrough", "Format ▸ Character", "strikeout"),
    cmd!(Superscript, "superscript", "Superscript", "Format ▸ Character"),
    cmd!(Subscript, "subscript", "Subscript", "Format ▸ Character"),
    cmd!(SmallCaps, "small-caps", "Small Caps", "Format ▸ Character"),
    cmd!(AllCaps, "all-caps", "All Caps", "Format ▸ Character"),
    cmd!(Font, "font", "Font…", "Format ▸ Character", "typeface"),
    cmd!(FontSize, "font-size", "Font Size…", "Format ▸ Character", "points"),
    cmd!(FontColor, "font-color", "Text Color…", "Format ▸ Character", "colour"),
    cmd!(Highlight, "highlight", "Highlight…", "Format ▸ Character"),
    cmd!(RemoveFormatting, "remove-formatting", "Remove Character Formatting", "Format ▸ Character", "clear plain"),
    cmd!(AlignLeft, "align-left", "Align Left", "Format ▸ Paragraph", "flush left justify"),
    cmd!(AlignCenter, "align-center", "Center", "Format ▸ Paragraph", "justify centre"),
    cmd!(AlignRight, "align-right", "Align Right", "Format ▸ Paragraph", "flush right justify"),
    cmd!(AlignJustify, "align-justify", "Justify (Full)", "Format ▸ Paragraph"),
    cmd!(Indent, "indent", "Increase Indent", "Format ▸ Paragraph", "left indent"),
    cmd!(Outdent, "outdent", "Decrease Indent", "Format ▸ Paragraph"),
    cmd!(IndentLeftRight, "indent-both", "Indent Left and Right", "Format ▸ Paragraph", "block quote"),
    cmd!(HangingIndent, "hanging-indent", "Hanging Indent", "Format ▸ Paragraph"),
    cmd!(ClearIndent, "clear-indent", "Remove Indents", "Format ▸ Paragraph", "clear reset left right first hanging"),
    cmd!(FirstLineIndent, "first-line-indent", "First Line Indent…", "Format ▸ Paragraph"),
    cmd!(SpacingSingle, "spacing-single", "Line Spacing: Single", "Format ▸ Paragraph"),
    cmd!(SpacingOneHalf, "spacing-1.5", "Line Spacing: 1.5", "Format ▸ Paragraph"),
    cmd!(SpacingDouble, "spacing-double", "Line Spacing: Double", "Format ▸ Paragraph"),
    cmd!(SpaceBefore, "space-before", "Space Before Paragraph…", "Format ▸ Paragraph"),
    cmd!(SpaceAfter, "space-after", "Space After Paragraph…", "Format ▸ Paragraph"),
    cmd!(KeepWithNext, "keep-with-next", "Keep With Next Paragraph", "Format ▸ Paragraph", "block protect"),
    cmd!(KeepLinesTogether, "keep-lines", "Keep Lines Together", "Format ▸ Paragraph"),
    cmd!(PageBreakBefore, "page-break-before", "Page Break Before Paragraph", "Format ▸ Paragraph"),
    cmd!(WidowOrphan, "widow-orphan", "Widow/Orphan Control", "Format ▸ Paragraph"),
    cmd!(TabSet, "tab-set", "Tab Stops…", "Format ▸ Paragraph"),
    cmd!(ListBullet, "list-bullet", "Bulleted List", "Format ▸ List", "bullets toggle"),
    cmd!(ListNumber, "list-number", "Numbered List", "Format ▸ List", "numbering toggle"),
    cmd!(ListFormat, "list-format", "List Numbering Format…", "Format ▸ List", "outline letters roman bullet style"),
    cmd!(ListIndent, "list-indent", "Increase List Level (Demote)", "Format ▸ List", "nest sub item"),
    cmd!(ListOutdent, "list-outdent", "Decrease List Level (Promote)", "Format ▸ List", "unnest"),
    cmd!(ListRestart, "list-restart", "Restart Numbering at 1", "Format ▸ List"),
    cmd!(ListContinue, "list-continue", "Continue Previous List", "Format ▸ List", "join numbering"),
    cmd!(ListRemove, "list-remove", "Remove from List", "Format ▸ List", "end list plain paragraph"),

    cmd!(ApplyStyle, "style", "Apply Style…", "Styles"),
    cmd!(StyleNormal, "style-normal", "Style: Normal", "Styles", "body"),
    cmd!(StyleHeading1, "style-heading-1", "Style: Heading 1", "Styles"),
    cmd!(StyleHeading2, "style-heading-2", "Style: Heading 2", "Styles"),
    cmd!(StyleHeading3, "style-heading-3", "Style: Heading 3", "Styles"),
    cmd!(StyleTitle, "style-title", "Style: Title", "Styles"),
    cmd!(StyleBrowser, "style-browser", "Style Browser (inheritance and overrides at cursor)", "Styles", "inspect"),
    cmd!(PageBreak, "page-break", "Insert Page Break", "Insert", "hard page"),
    cmd!(LineBreak, "line-break", "Insert Line Break", "Insert", "soft return"),
    cmd!(InsertTab, "tab", "Insert Tab", "Insert"),
    cmd!(Bookmark, "bookmark", "Insert Bookmark…", "Insert"),
    cmd!(Date, "date", "Insert Date", "Insert", "today"),
    cmd!(TableInsert, "table-insert", "Table: Insert…", "Table", "new create grid"),
    cmd!(TableNextCell, "table-next-cell", "Table: Next Cell", "Table", "tab"),
    cmd!(TablePrevCell, "table-prev-cell", "Table: Previous Cell", "Table", "shift tab"),
    cmd!(TableInsertRowBelow, "table-insert-row-below", "Table: Insert Row Below", "Table"),
    cmd!(TableInsertRowAbove, "table-insert-row-above", "Table: Insert Row Above", "Table"),
    cmd!(TableInsertColRight, "table-insert-col-right", "Table: Insert Column Right", "Table"),
    cmd!(TableInsertColLeft, "table-insert-col-left", "Table: Insert Column Left", "Table"),
    cmd!(TableDeleteRow, "table-delete-row", "Table: Delete Row", "Table"),
    cmd!(TableDeleteCol, "table-delete-col", "Table: Delete Column", "Table"),
    cmd!(TableDelete, "table-delete", "Table: Delete Table", "Table", "remove"),
    cmd!(TableToText, "table-to-text", "Table: Convert to Text (tab-separated)", "Table", "tbl def"),
    cmd!(TableColWidth, "table-col-width", "Table: Column Width…", "Table", "resize"),
    cmd!(TableHeaderRow, "table-header-row", "Table: Repeat Row as Header on Each Page", "Table", "heading"),
    cmd!(SectionBreakNextPage, "section-break", "Insert Section Break (New Page)", "Format ▸ Page", "sect next"),
    cmd!(SectionBreakContinuous, "section-break-continuous", "Insert Section Break (Continuous)", "Format ▸ Page", "sect same page"),
    cmd!(SectionBreakOddPage, "section-break-odd", "Insert Section Break (Odd Page)", "Format ▸ Page", "sect right"),
    cmd!(SectionBreakEvenPage, "section-break-even", "Insert Section Break (Even Page)", "Format ▸ Page", "sect left"),
    cmd!(ColumnsOne, "columns-one", "Columns: One", "Format ▸ Page", "single column"),
    cmd!(ColumnsTwo, "columns-two", "Columns: Two", "Format ▸ Page", "newspaper"),
    cmd!(ColumnsThree, "columns-three", "Columns: Three", "Format ▸ Page", "newspaper"),
    cmd!(HeaderEdit, "header-edit", "Header: Edit (every page)", "Format ▸ Page", "running head top"),
    cmd!(HeaderEditFirst, "header-edit-first", "Header: Edit First-Page Header", "Format ▸ Page", "title page"),
    cmd!(HeaderEditEven, "header-edit-even", "Header: Edit Even-Page Header", "Format ▸ Page", "odd even facing"),
    cmd!(FooterEdit, "footer-edit", "Footer: Edit (every page)", "Format ▸ Page", "bottom page number"),
    cmd!(FooterEditFirst, "footer-edit-first", "Footer: Edit First-Page Footer", "Format ▸ Page", "title page"),
    cmd!(FooterEditEven, "footer-edit-even", "Footer: Edit Even-Page Footer", "Format ▸ Page", "odd even facing"),
    cmd!(HeaderFooterDone, "header-footer-done", "Header/Footer: Return to Document", "Format ▸ Page", "close exit done"),
    cmd!(HeaderRemove, "header-remove", "Header: Remove from This Section", "Format ▸ Page", "delete discontinue"),
    cmd!(FooterRemove, "footer-remove", "Footer: Remove from This Section", "Format ▸ Page", "delete discontinue"),
    cmd!(TitlePage, "title-page", "Different First Page Header/Footer (toggle)", "Format ▸ Page", "title page suppress"),
    cmd!(EvenOddHeaders, "even-odd-headers", "Different Odd and Even Headers/Footers (toggle)", "Format ▸ Page", "facing pages"),
    cmd!(InsertPageNumber, "insert-page-number", "Insert Page Number", "Insert", "page field"),
    cmd!(InsertPageCount, "insert-page-count", "Insert Page Count (NUMPAGES)", "Insert", "total pages field of"),
    cmd!(PageSetup, "page-setup", "Page Setup (margins)…", "Format ▸ Page"),
    cmd!(PaperLetter, "paper-letter", "Paper Size: US Letter", "Format ▸ Page"),
    cmd!(PaperA4, "paper-a4", "Paper Size: A4", "Format ▸ Page"),
    cmd!(Portrait, "portrait", "Orientation: Portrait", "Format ▸ Page"),
    cmd!(Landscape, "landscape", "Orientation: Landscape", "Format ▸ Page"),
    cmd!(Margins, "margins", "Margins…", "Format ▸ Page"),
    cmd!(RevealCodes, "reveal-codes", "Reveal Codes", "View", "show formatting"),
    cmd!(RevealAllCodes, "reveal-all-codes", "Reveal Codes: Show Preserved Run Properties", "View", "raw"),
    cmd!(ToggleView, "toggle-view", "Switch Draft / Page View", "View"),
    cmd!(ToggleWrap, "toggle-wrap", "Wrap Lines: Page Width / Terminal Width", "View", "line breaks draft screen"),
    cmd!(FkeyLegend, "fkey-legend", "F-Key Legend (keyboard template)", "View", "template card"),
    cmd!(MenuBar, "menu-bar", "Menu Bar (always shown)", "View", "pull-down menus pin toggle"),
    cmd!(ThemeDefault, "theme-default", "Theme: Terminal Default", "View", "colors colours"),
    cmd!(ThemeClassic, "theme-classic", "Theme: Classic WordPerfect (blue screen)", "View", "colors colours dos 5.1"),
    cmd!(WordCount, "word-count", "Word Count", "View", "statistics"),
    cmd!(Redraw, "redraw", "Redraw Screen", "View", "rewrite refresh"),
    cmd!(Palette, "palette", "Command Palette", "Navigate"),
    cmd!(Menu, "menu", "Menu (pull-down menus)", "Navigate", "menubar file edit"),
    cmd!(GoToPage, "goto-page", "Go to Page…", "Navigate"),
    cmd!(GoToHeading, "goto-heading", "Go to Heading…", "Navigate", "outline"),
    cmd!(GoToBookmark, "goto-bookmark", "Go to Bookmark…", "Navigate"),
    cmd!(Find, "find", "Find…", "Navigate", "search"),
    cmd!(FindBackward, "find-backward", "Find Backward…", "Navigate", "search"),
    cmd!(FindNext, "find-next", "Find Next", "Navigate"),
    cmd!(FindPrev, "find-prev", "Find Previous", "Navigate"),
    cmd!(Replace, "replace", "Replace… (preview, then all or one at a time)", "Navigate", "search and replace"),
    cmd!(FindRegex, "find-regex", "Find with Regular Expression…", "Navigate ▸ Find", "regex pattern capture groups"),
    cmd!(FindToggleCase, "find-toggle-case", "Find Option: Match Case", "Navigate ▸ Find", "sensitive"),
    cmd!(FindToggleWord, "find-toggle-word", "Find Option: Whole Words", "Navigate ▸ Find"),
    cmd!(FindToggleRegex, "find-toggle-regex", "Find Option: Regular Expressions", "Navigate ▸ Find"),
    cmd!(FindBold, "find-bold", "Find Bold Text", "Navigate ▸ Find", "formatting"),
    cmd!(FindItalic, "find-italic", "Find Italic Text", "Navigate ▸ Find", "formatting"),
    cmd!(FindUnderlined, "find-underlined", "Find Underlined Text", "Navigate ▸ Find", "formatting"),
    cmd!(FindHighlighted, "find-highlighted", "Find Highlighted Text", "Navigate ▸ Find", "formatting"),
    cmd!(FindInStyle, "find-in-style", "Find Text in Style…", "Navigate ▸ Find", "heading"),
    cmd!(FindCode, "find-code", "Find Code…", "Navigate ▸ Find", "reveal codes"),
    cmd!(FindPageBreak, "find-page-break", "Find Next Page Break", "Navigate ▸ Find", "code hpg"),
    cmd!(FindTab, "find-tab", "Find Next Tab", "Navigate ▸ Find", "code"),
    cmd!(FindLineBreak, "find-line-break", "Find Next Line Break", "Navigate ▸ Find", "code soft return"),

    cmd!(DocStart, "doc-start", "Top of Document", "Navigate"),
    cmd!(DocEnd, "doc-end", "Bottom of Document", "Navigate"),
    cmd!(NextPage, "next-page", "Next Page", "Navigate"),
    cmd!(PrevPage, "prev-page", "Previous Page", "Navigate"),
    cmd!(PageUp, "page-up", "Screen Up", "Navigate"),
    cmd!(PageDown, "page-down", "Screen Down", "Navigate"),
    cmd!(ParaUp, "para-up", "Previous Paragraph", "Navigate"),
    cmd!(ParaDown, "para-down", "Next Paragraph", "Navigate"),
    cmd!(WordLeft, "word-left", "Word Left", "Navigate"),
    cmd!(WordRight, "word-right", "Word Right", "Navigate"),
    cmd!(LineStart, "line-start", "Start of Line", "Navigate"),
    cmd!(LineEnd, "line-end", "End of Line", "Navigate"),
    cmd!(hidden MoveLeft, "left", "Left", "Navigate"),
    cmd!(hidden MoveRight, "right", "Right", "Navigate"),
    cmd!(hidden MoveUp, "up", "Up", "Navigate"),
    cmd!(hidden MoveDown, "down", "Down", "Navigate"),
    cmd!(hidden SelectLeft, "select-left", "Select Left", "Edit"),
    cmd!(hidden SelectRight, "select-right", "Select Right", "Edit"),
    cmd!(hidden SelectUp, "select-up", "Select Up", "Edit"),
    cmd!(hidden SelectDown, "select-down", "Select Down", "Edit"),
    cmd!(hidden SelectWordLeft, "select-word-left", "Select Word Left", "Edit"),
    cmd!(hidden SelectWordRight, "select-word-right", "Select Word Right", "Edit"),
    cmd!(hidden SelectLineStart, "select-line-start", "Select to Start of Line", "Edit"),
    cmd!(hidden SelectLineEnd, "select-line-end", "Select to End of Line", "Edit"),
    cmd!(hidden SelectDocStart, "select-doc-start", "Select to Top", "Edit"),
    cmd!(hidden SelectDocEnd, "select-doc-end", "Select to Bottom", "Edit"),
    cmd!(hidden SelectPageUp, "select-page-up", "Select Screen Up", "Edit"),
    cmd!(hidden SelectPageDown, "select-page-down", "Select Screen Down", "Edit"),
    cmd!(hidden Backspace, "backspace", "Backspace", "Edit"),
    cmd!(hidden Delete, "delete", "Delete", "Edit"),
    cmd!(hidden Enter, "enter", "New Paragraph", "Edit"),
    cmd!(KeyboardModern, "keyboard-modern", "Keyboard: Modern (Ctrl+S, Ctrl+B…)", "Help", "keymap"),
    cmd!(KeyboardClassic, "keyboard-classic", "Keyboard: Classic (WordPerfect 5.1 F-keys)", "Help", "keymap"),
    cmd!(Help, "help", "Help", "Help", "keys"),
    cmd!(About, "about", "About wp", "Help", "version"),
    cmd!(RepeatPrefix, "repeat", "Repeat Count Prefix (Esc n)", "Edit", "classic"),
];

pub fn by_key(key: &str) -> Option<Cmd> {
    COMMANDS.iter().find(|c| c.key == key).map(|c| c.id)
}

pub fn info(id: Cmd) -> &'static Command {
    COMMANDS.iter().find(|c| c.id == id).expect("every Cmd is registered")
}
