#!/usr/bin/env python3
"""Generate embedded font-metric tables for wp-core.

Reads TrueType fonts (no third-party deps: parses head/hhea/hmtx/cmap/OS2
directly) and writes crates/wp-core/src/metrics/tables.rs containing, for each
font, advance widths in 1/1000 em for U+0020..U+024F plus a set of common
punctuation, and the font's line-height factor.

Usage: fontgen.py <out.rs> <name>=<regular.ttf>[,<bold.ttf>] ...
"""
import struct
import sys

# Codepoints covered by the tables: Basic Latin, Latin-1, Latin Extended-A/B,
# plus general punctuation and symbols that appear in real documents.
RANGES = [(0x20, 0x24F)]
EXTRA = [0x2010, 0x2011, 0x2012, 0x2013, 0x2014, 0x2018, 0x2019, 0x201A,
         0x201C, 0x201D, 0x201E, 0x2020, 0x2021, 0x2022, 0x2026, 0x2030,
         0x2039, 0x203A, 0x20AC, 0x2122, 0x2212, 0x00A0, 0x2032, 0x2033]


def tables(data):
    num = struct.unpack(">H", data[4:6])[0]
    out = {}
    for i in range(num):
        off = 12 + 16 * i
        tag = data[off:off + 4].decode("latin1")
        toff, tlen = struct.unpack(">II", data[off + 8:off + 16])
        out[tag] = data[toff:toff + tlen]
    return out


def parse_cmap(cmap):
    n = struct.unpack(">H", cmap[2:4])[0]
    best = None
    for i in range(n):
        pid, eid, off = struct.unpack(">HHI", cmap[4 + 8 * i:12 + 8 * i])
        fmt = struct.unpack(">H", cmap[off:off + 2])[0]
        if (pid, eid) in ((3, 1), (0, 3), (0, 4), (0, 6)) and fmt == 4:
            best = off
    if best is None:
        raise SystemExit("no format-4 cmap")
    sub = cmap[best:]
    segx2 = struct.unpack(">H", sub[6:8])[0]
    seg = segx2 // 2
    ends = struct.unpack(f">{seg}H", sub[14:14 + segx2])
    starts = struct.unpack(f">{seg}H", sub[16 + segx2:16 + 2 * segx2])
    deltas = struct.unpack(f">{seg}h", sub[16 + 2 * segx2:16 + 3 * segx2])
    ro_off = 16 + 3 * segx2
    ros = struct.unpack(f">{seg}H", sub[ro_off:ro_off + segx2])
    m = {}
    for i in range(seg):
        for c in range(starts[i], min(ends[i], 0xFFFE) + 1):
            if ros[i] == 0:
                g = (c + deltas[i]) & 0xFFFF
            else:
                gi = ro_off + 2 * i + ros[i] + 2 * (c - starts[i])
                if gi + 2 > len(sub):
                    continue
                g = struct.unpack(">H", sub[gi:gi + 2])[0]
                if g:
                    g = (g + deltas[i]) & 0xFFFF
            if g:
                m[c] = g
    return m


def load(path):
    data = open(path, "rb").read()
    t = tables(data)
    upem = struct.unpack(">H", t["head"][18:20])[0]
    nhm = struct.unpack(">H", t["hhea"][34:36])[0]
    hmtx = t["hmtx"]
    adv = [struct.unpack(">H", hmtx[4 * i:4 * i + 2])[0] for i in range(nhm)]
    cmap = parse_cmap(t["cmap"])
    os2 = t["OS/2"]
    win_asc, win_desc = struct.unpack(">HH", os2[74:78])
    # hhea ascender/descender/lineGap as a cross-check
    asc, desc, gap = struct.unpack(">hhh", t["hhea"][4:10])

    def width(c):
        g = cmap.get(c)
        if g is None:
            return None
        a = adv[min(g, nhm - 1)]
        return round(a * 1000 / upem)

    cps = sorted(set([c for lo, hi in RANGES for c in range(lo, hi + 1)] + EXTRA))
    widths = [width(c) for c in cps]
    known = [w for w in widths if w is not None]
    avg = round(sum(known) / len(known))
    x_avg = round(sum(width(ord(c)) or 0 for c in "abcdefghijklmnopqrstuvwxyz") / 26)
    lh = (win_asc + win_desc) / upem
    return cps, [w if w is not None else 0 for w in widths], avg, x_avg, lh


def main():
    out = sys.argv[1]
    specs = sys.argv[2:]
    lines = ["// Generated by tools/fontgen.py — do not edit.",
             "// Advance widths in 1/1000 em. Metrics from OFL-licensed",
             "// metric-compatible fonts (Liberation, Carlito, Caladea).",
             "", "use crate::metrics::FontTable;", ""]
    names = []
    for spec in specs:
        name, files = spec.split("=")
        files = files.split(",")
        cps, reg, avg, xavg, lh = load(files[0])
        if len(files) > 1:
            _, bold, bavg, _, _ = load(files[1])
        else:
            bold, bavg = reg, avg
        const = name.upper().replace(" ", "_").replace("-", "_")
        names.append((name, const))
        lines.append(f"pub static {const}: FontTable = FontTable {{")
        lines.append(f"    name: \"{name}\",")
        lines.append(f"    line_height: {lh:.4f},")
        lines.append(f"    avg_width: {avg},")
        lines.append(f"    avg_width_bold: {bavg},")
        lines.append(f"    codepoints: &{cps!r},".replace("[", "[").replace(", ", ","))
        lines.append(f"    widths: &{reg!r},".replace(", ", ","))
        lines.append(f"    widths_bold: &{bold!r},".replace(", ", ","))
        lines.append("};")
        lines.append("")
    lines.append("pub static ALL: &[&FontTable] = &[" + ", ".join(f"&{c}" for _, c in names) + "];")
    lines.append("")
    open(out, "w").write("\n".join(lines))
    for n, _ in names:
        print("wrote", n)


if __name__ == "__main__":
    main()
