#!/usr/bin/env python3
"""Generate KEYBINDINGS.md from the tables in crates/wp/src/keymap.rs and the
command registry in crates/wp/src/commands.rs. Run after changing either."""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
keymap = (root / "crates/wp/src/keymap.rs").read_text()
commands = (root / "crates/wp/src/commands.rs").read_text()

titles = {}
for m in re.finditer(r'cmd!\((?:hidden )?\w+, "([^"]+)", "([^"]+)", "([^"]+)"', commands):
    titles[m.group(1)] = (m.group(2), m.group(3))


def table(name):
    m = re.search(r"const %s: &\[\(&str, &str\)\] = &\[(.*?)\];" % name, keymap, re.S)
    return re.findall(r'\("([^"]+)", "([^"]+)"\)', m.group(1))


def label(k):
    parts = k[:-2].split("+") + ["+"] if k.endswith("++") else k.split("+")
    out = []
    for p in parts:
        out.append({"ctrl": "Ctrl", "alt": "Alt", "shift": "Shift", "cmd": "Cmd", "esc": "Esc", "enter": "Enter",
                    "backspace": "Backspace", "delete": "Del", "insert": "Ins", "pageup": "PgUp",
                    "pagedown": "PgDn", "left": "←", "right": "→", "up": "↑", "down": "↓",
                    "home": "Home", "end": "End", "tab": "Tab", "space": "Space"}.get(p, p.upper()))
    return "+".join(out)


def rows(pairs):
    seen = set()
    out = []
    for k, c in pairs:
        t, cat = titles.get(c, (c, ""))
        out.append(f"| `{label(k)}` | {t} | {cat} |")
        seen.add(c)
    return out, seen


common, seen_common = rows(table("COMMON"))
classic, seen_classic = rows(table("CLASSIC"))
modern, seen_modern = rows(table("MODERN"))
mac, seen_mac = rows(table("MAC"))
all_bound = seen_common | seen_classic | seen_modern | seen_mac
unbound = [t for key, (t, cat) in titles.items() if key not in all_bound]

doc = ["# wp keybindings", "",
       "Generated by `tools/gen_keybindings.py` from the tables in `crates/wp/src/keymap.rs`. "
       "Every command is also reachable from the palette (`Ctrl+Shift+P` modern, `Ctrl+K` classic), which shows these keys. "
       "Override any binding in `~/.config/wp/config.toml` under `[bindings]`, e.g. "
       "`\"ctrl+shift+b\" = \"bold\"`; bind a key to `\"\"` to unbind it.", "",
       "Modified F-keys need a terminal that reports them (most do; the kitty keyboard protocol "
       "is used where available). On macOS set your terminal's Option key to act as Meta/Alt for `Alt+…` bindings.", "",
       "## Both keyboards", "", "| Key | Command | Category |", "|---|---|---|", *common, "",
       "## Classic (WordPerfect 5.1)", "",
       "Selected with `keymap = \"classic\"`. `Esc` followed by a number repeats the next key that many times.", "",
       "| Key | Command | Category |", "|---|---|---|", *classic, "",
       "## Modern", "",
       "Selected with `keymap = \"modern\"` (the default). Movement and deletion follow emacs / macOS readline "
       "conventions: `Ctrl+F/B/N/P/A/E`, `Alt+F/B`, `Ctrl+D/H/K/U`, `Alt+D`, `Ctrl+W`/`Alt+W`/`Ctrl+Y`. "
       "All Classic bindings above remain active underneath; the rows below are added on top and win on conflict "
       "(`Esc` cancels rather than starting a repeat count, `F1` is help, `F3` is find-next, and the palette is "
       "`Ctrl+Shift+P` because `Ctrl+K` is kill-line). On macOS set the terminal's Option key to Meta for `Alt+…`.", "",
       "| Key | Command | Category |", "|---|---|---|", *modern, "",
       "### Cmd layer (macOS)", "",
       "Part of the modern map. Delivered only by terminals that report the Cmd key through the kitty keyboard "
       "protocol (Ghostty, kitty, WezTerm); the terminal's own Cmd shortcuts take precedence — in Ghostty, free one "
       "with e.g. `keybind = cmd+k=unbind`. Ghostty also translates `Cmd+Backspace`, `Cmd+←`, `Cmd+→` into "
       "`Ctrl+U`, `Ctrl+A`, `Ctrl+E` by default, which the modern map handles the same way. Run `wp --probe-keys` "
       "to see what your terminal sends.", "",
       "| Key | Command | Category |", "|---|---|---|", *mac, "",
       "## Palette only", "", "Commands with no default key in either map:", "",
       *[f"- {t}" for t in sorted(unbound)], ""]
(root / "KEYBINDINGS.md").write_text("\n".join(doc))
print("wrote KEYBINDINGS.md:", len(common), "common,", len(classic), "classic,", len(modern), "modern,", len(unbound), "palette-only")
